name: AppPack Deploy
description: Trigger an AppPack deploy
branding:
  icon: box
  color: purple
inputs:
  appname:
    description: Name of the AppPack app
    required: true
  image:
    description: Docker image to deploy
    required: true
outputs:
  build_number:
    description: CodeBuild build number of deploy
  build_arn:
    description: CodeBuild build ARN of deploy
runs:
  using: node16
  main: index.js
